### ISSUE TITLE
2.3 Features

### ISSUE THREAD

**Issue by TheGoodDude22** [TheGoodDude22/AbigailBot#17]
### 2.3 TODO

- [x] Command Groups
- [x] Moderation Commands
- [x] custom Join to Create channels
- [ ] Custom moderator roles
- [ ] ? - Music DJ
- [x] ? - Enable/disable game commands
- [x] ? - E/D fun commands
